Path = 'C:\Users\dkovari\Desktop\explant\20161209explant\MO';
File = 'sample005.nd2';
RefFile = 'sample005sds.nd2';
[~,name,~] = fileparts(File);
OutDir = fullfile(Path,name);
mkdir(OutDir);

Series = [1:3];

BeadChan = 2;
CellChan = 1;
RefFrame = 'last';
X_CROP = 'full';
Y_CROP = 'full';
bpass_lnoise = 1;
bpass_sz = 7;
pkfnd_sz = 7;
pkfnd_th = 60;
YoungE = 7.2e3;
PoissonV = .46;

for s=Series
    TFMdata = CalculateTFM_piv('FilePath',fullfile(Path,File),...
        'Reference',fullfile(Path,RefFile),...
        'SavePath',fullfile(OutDir,sprintf('%s_xy%d.mat',name,s)),...
        'ForceMoviePath',fullfile(OutDir,sprintf('%s_xy%d.mp4',name,s)),...
        'SeriesNum',s,...
        'RefSeries',s,...
        'RefFrame',RefFrame,...
        'CellChan',CellChan,...
        'BeadChan',BeadChan,...
        'RefChan',BeadChan,...
        'X_CROP',X_CROP,...
        'Y_CROP',Y_CROP,...
        'bpass_lnoise',bpass_lnoise,...
        'bpass_sz',bpass_sz,...
        'pkfnd_sz',pkfnd_sz,...
        'pkfnd_th',pkfnd_th,...
        'YoungE',YoungE,...
        'PoissonV',PoissonV,...
        'CellImageCLim',[650,1600],...
        'SMAGLim',[0,3000],...
        'PlotStrain',true);
end


