[f,p] = uigetfile('*.mat');

data = load(fullfile(p,f));

bad = data.SED>0.001|...
    abs(data.Vqx)>10|...
    abs(data.Vqy)>10|...
    isnan(data.SED)|...
    isnan(data.Vqx)|...
    isnan(data.Vqy);

data.SED(bad) = NaN;
data.Vqx(bad) = NaN;
data.Vqy(bad) = NaN;
%% h
[~,f,ext] = fileparts(f);
f = [f,'.mp4'];

TFMForceViewer(data,...
            'CellImageCLim',[650,1600],...
            'PlotStrain',true,...
            'MapData','StrainEnergyDensity',...
            'MapLim',[0,6e-4],...
            'MoviePath',fullfile(p,f),...
            'MovieQuality',100,...
            'FigureSize',round([1280,1010]));